### ISSUE TITLE
Windows: Multiple instances of Gitter

### ISSUE THREAD

**Issue by quassy** [gitterHQ/desktop#24]
Apparently Gitter does not check if it (or at least its daemon) is already running: If I close to tray and then restart Gitter from the taskbar (pinned app) a new instance is launched instead of reopening the existing one. 

(Running multiple instances would only be a feature when using multiple accounts... Gitter for Windows; Windows 8.1)

**Comment by MadLittleMods** [comment]
I kinda like this flexibility to have multiple instances although, it is weird that you have to close the main chat window for it to work. 

I have tested and can replicate these effects on a Windows 8.1 64 bit system.

**Comment by suprememoocow** [comment]
This should be pretty easy to do by changing the nw.js manifest by changing this line to `true`:
https://github.com/gitterHQ/desktop/blob/master/nwapp/package.json#L47

Read more here:
https://github.com/nwjs/nw.js/wiki/manifest-format#single-instance

**Comment by suprememoocow** [comment]
@trevorah is planning on doing a release before the end of the week hopefully. This should be fixed in that release. Sorry about the delay in getting this done @quassy!

**Comment by trevorah** [comment]
:balloon: Everything sucks! :balloon:

Turns out that fixing this breaks #74, as `node-webkit-updater` requires multiple running instances in order to apply updates (https://github.com/edjafarov/node-webkit-updater/issues/62). Having working autoupdates takes priority.

**Comment by DrLeh** [comment]
This is still happening today, more than a year later... any chance we can prioritize this?
